spring.application.name=login

# HS512 secret key
# [개선] 환경변수 우선, 기본값 fallback
com.aloha.login.secret-key=${JWT_SECRET_KEY:2Pyq[MyRMH(DxP'K)ONVI\LB29GD:xbB]?`\{ogZ[}#*)hx7/~68FxK2)HJdCPZ#A&[CBg{v9+T2c122}